### ISSUE TITLE
Would there be an option to swap out the BME280 for BME680 which monitors CO?

### ISSUE THREAD

**Issue by rshxyz** [WesleyE/AirQuality_Monitor#3]
Would there be an option to swap out the BME280 for BME680 which monitors CO among other things? 

CO2meter lists other sensors but are way more expensive to monitor carbon monoxide
https://www.co2meter.com/collections/co-sensors

An article that talks about CO sensors 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6541011/

Specs of BME680 but Adafruit also has one
https://www.waveshare.com/wiki/BME680_Environmental_Sensor

**Comment by WesleyE** [comment]
Yes I thought about adding a CO sensor but ultimately decided not to:

- I already had commercial CO monitors
- I did not want to be tempted to just use my own and have even the slightest possibility to die from a leak because of some silly bug I introduced

The BME680, if I'm not mistaken, has no separate readout for just CO.
